//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordpressDrive.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordpressDrive.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow unsecure SSL certs ähnelt.
        /// </summary>
        public static string allow_unsecure_ssl {
            get {
                return ResourceManager.GetString("allow_unsecure_ssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die anonymous login ähnelt.
        /// </summary>
        public static string Anonymous_Login {
            get {
                return ResourceManager.GetString("Anonymous_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attachments ähnelt.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close when finished ähnelt.
        /// </summary>
        public static string autoclose_sync_dialog {
            get {
                return ResourceManager.GetString("autoclose_sync_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die basic settings ähnelt.
        /// </summary>
        public static string basic_settings {
            get {
                return ResourceManager.GetString("basic_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cache these item types: ähnelt.
        /// </summary>
        public static string cache_these_itemtypes {
            get {
                return ResourceManager.GetString("cache_these_itemtypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Settings ähnelt.
        /// </summary>
        public static string close_settings {
            get {
                return ResourceManager.GetString("close_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect/disconnect default Host ähnelt.
        /// </summary>
        public static string connect_default_host {
            get {
                return ResourceManager.GetString("connect_default_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection ähnelt.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Directory does not exist ähnelt.
        /// </summary>
        public static string directory_not_exist {
            get {
                return ResourceManager.GetString("directory_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display Name ähnelt.
        /// </summary>
        public static string display_name {
            get {
                return ResourceManager.GetString("display_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die synchronize! ähnelt.
        /// </summary>
        public static string do_synchronize {
            get {
                return ResourceManager.GetString("do_synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete ähnelt.
        /// </summary>
        public static string do_you_want_delete {
            get {
                return ResourceManager.GetString("do_you_want_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drive ähnelt.
        /// </summary>
        public static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request cancelled, network error or server not responding ähnelt.
        /// </summary>
        public static string err_msg_network {
            get {
                return ResourceManager.GetString("err_msg_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error validating SSL certificate ähnelt.
        /// </summary>
        public static string err_msg_ssl {
            get {
                return ResourceManager.GetString("err_msg_ssl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Server error ähnelt.
        /// </summary>
        public static string err_unknow_server_error {
            get {
                return ResourceManager.GetString("err_unknow_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die error ähnelt.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die extended settings ähnelt.
        /// </summary>
        public static string extended_settings {
            get {
                return ResourceManager.GetString("extended_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die filename ähnelt.
        /// </summary>
        public static string filename {
            get {
                return ResourceManager.GetString("filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host ähnelt.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon Mouse Actions: ähnelt.
        /// </summary>
        public static string icon_mouse_actions {
            get {
                return ResourceManager.GetString("icon_mouse_actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default Host ähnelt.
        /// </summary>
        public static string is_default_host {
            get {
                return ResourceManager.GetString("is_default_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left click: ähnelt.
        /// </summary>
        public static string left_mb_click {
            get {
                return ResourceManager.GetString("left_mb_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Left dblclick: ähnelt.
        /// </summary>
        public static string left_mb_dblclick {
            get {
                return ResourceManager.GetString("left_mb_dblclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login cancelled by User ähnelt.
        /// </summary>
        public static string Login_cancelled {
            get {
                return ResourceManager.GetString("Login_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed, please try again ähnelt.
        /// </summary>
        public static string Login_failed_retry {
            get {
                return ResourceManager.GetString("Login_failed_retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Items per Directory ähnelt.
        /// </summary>
        public static string max_items_per_directory {
            get {
                return ResourceManager.GetString("max_items_per_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to omit all your changes? ähnelt.
        /// </summary>
        public static string msgbox_omit_sync_question {
            get {
                return ResourceManager.GetString("msgbox_omit_sync_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not connected ähnelt.
        /// </summary>
        public static string not_connected {
            get {
                return ResourceManager.GetString("not_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die omit synchronize ähnelt.
        /// </summary>
        public static string omit_synchronize {
            get {
                return ResourceManager.GetString("omit_synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Cache Directory ähnelt.
        /// </summary>
        public static string open_cache_directory {
            get {
                return ResourceManager.GetString("open_cache_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Config Directory ähnelt.
        /// </summary>
        public static string open_config_directory {
            get {
                return ResourceManager.GetString("open_config_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Popupmenu ähnelt.
        /// </summary>
        public static string open_popupmenu {
            get {
                return ResourceManager.GetString("open_popupmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Settings ähnelt.
        /// </summary>
        public static string open_settings {
            get {
                return ResourceManager.GetString("open_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other items ähnelt.
        /// </summary>
        public static string other_items {
            get {
                return ResourceManager.GetString("other_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die outstanding synchronizations! ähnelt.
        /// </summary>
        public static string Outstanding_synchronizations {
            get {
                return ResourceManager.GetString("Outstanding_synchronizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an item ähnelt.
        /// </summary>
        public static string please_select_item {
            get {
                return ResourceManager.GetString("please_select_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request retries ähnelt.
        /// </summary>
        public static string request_retries {
            get {
                return ResourceManager.GetString("request_retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Request timeout ähnelt.
        /// </summary>
        public static string request_timeout {
            get {
                return ResourceManager.GetString("request_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Right click: ähnelt.
        /// </summary>
        public static string right_mb_click {
            get {
                return ResourceManager.GetString("right_mb_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select ähnelt.
        /// </summary>
        public static string select_sync_item {
            get {
                return ResourceManager.GetString("select_sync_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show connect message ähnelt.
        /// </summary>
        public static string show_connect_msg {
            get {
                return ResourceManager.GetString("show_connect_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Dialog ähnelt.
        /// </summary>
        public static string show_sync_dialog {
            get {
                return ResourceManager.GetString("show_sync_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die state ähnelt.
        /// </summary>
        public static string state_sync_item {
            get {
                return ResourceManager.GetString("state_sync_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully connected with &apos;{0}&apos; ähnelt.
        /// </summary>
        public static string successfully_connect_msg {
            get {
                return ResourceManager.GetString("successfully_connect_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supply Login Information or choose anonymous Login ähnelt.
        /// </summary>
        public static string Supply_auth_data {
            get {
                return ResourceManager.GetString("Supply_auth_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronization Dialog: ähnelt.
        /// </summary>
        public static string sync_dialog {
            get {
                return ResourceManager.GetString("sync_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronize ähnelt.
        /// </summary>
        public static string Synchronize {
            get {
                return ResourceManager.GetString("Synchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronize Changes ähnelt.
        /// </summary>
        public static string syncronize_changes {
            get {
                return ResourceManager.GetString("syncronize_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Synchronizing ähnelt.
        /// </summary>
        public static string syncronizing_caching {
            get {
                return ResourceManager.GetString("syncronizing_caching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System ähnelt.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die close ähnelt.
        /// </summary>
        public static string task_close {
            get {
                return ResourceManager.GetString("task_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die create ähnelt.
        /// </summary>
        public static string task_create {
            get {
                return ResourceManager.GetString("task_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete ähnelt.
        /// </summary>
        public static string task_delete {
            get {
                return ResourceManager.GetString("task_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die modify ähnelt.
        /// </summary>
        public static string task_modify {
            get {
                return ResourceManager.GetString("task_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rename ähnelt.
        /// </summary>
        public static string task_rename {
            get {
                return ResourceManager.GetString("task_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die task ähnelt.
        /// </summary>
        public static string task_sync_item {
            get {
                return ResourceManager.GetString("task_sync_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creates a new host entry ähnelt.
        /// </summary>
        public static string tt_create_host {
            get {
                return ResourceManager.GetString("tt_create_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removes the currently selected host ähnelt.
        /// </summary>
        public static string tt_delete_host {
            get {
                return ResourceManager.GetString("tt_delete_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die type ähnelt.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umount Drive ähnelt.
        /// </summary>
        public static string umount_drive {
            get {
                return ResourceManager.GetString("umount_drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown error could not connect to {0} ähnelt.
        /// </summary>
        public static string Unknow_connect_error {
            get {
                return ResourceManager.GetString("Unknow_connect_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User interface ähnelt.
        /// </summary>
        public static string Userinterface {
            get {
                return ResourceManager.GetString("Userinterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die warning ähnelt.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wordpress link ähnelt.
        /// </summary>
        public static string wordpress_link {
            get {
                return ResourceManager.GetString("wordpress_link", resourceCulture);
            }
        }
    }
}
