version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

platform:
- x86
- x64
    
before_build:
- start /wait msiexec /i WordpressDriveBoot\external\winfsp-1.7.20172.msi /qn ADDLOCAL=ALL
- cmd: nuget restore

build:
  verbosity: normal
  parallel: true

artifacts: 
  - path: WordpressDrive\bin\$(configuration)
    name: WordpressDriveFiles
  - path: WordpressDriveSetup\bin\$(configuration)\WordpressDriveSetup.msi
    name: WordpressDriveSetup.msi
  - path: WordpressDriveBoot\bin\$(configuration)\WordpressDriveSetup.exe
    name: WordpressDriveFull.exe
  - path: WordpressDrive\bin\$(platform)\$(configuration)
    name: WordpressDriveFiles_x64
#  - path: WordpressDriveSetup\bin\$(platform)\$(configuration)\WordpressDriveSetup_64.msi
#    name: WordpressDriveSetup_x64.msi
#  - path: WordpressDriveBoot\bin\$(platform)\$(configuration)\WordpressDriveSetup_64.exe
#    name: WordpressDriveFull_x64.exe
    
after_build:
- ps: >-
    $fileToCheck = "WordpressDriveSetup\bin\x64\Release\WordpressDriveSetup.msi"
    if (Test-Path $fileToCheck -PathType leaf)
    {
        appveyor PushArtifact WordpressDriveSetup\bin\x64\Release\WordpressDriveSetup.msi -FileName WordpressDriveSetup\bin\x64\Release\WordpressDriveSetup_x64.msi
    }
    $fileToCheck = "WordpressDriveBoot\bin\x64\Release\WordpressDriveSetup.exe"
    if (Test-Path $fileToCheck -PathType leaf)
    {
        appveyor PushArtifact WordpressDriveBoot\bin\x64\Release\WordpressDriveSetup.exe -FileName WordpressDriveBoot\bin\x64\Release\WordpressDriveSetup_64.exe
    }
    
#- appveyor PushArtifact WordpressDriveSetup\bin\x64\Release\WordpressDriveSetup.msi -FileName WordpressDriveSetup\bin\x64\Release\WordpressDriveSetup_x64.msi
#- appveyor PushArtifact WordpressDriveBoot\bin\x64\Release\WordpressDriveSetup.exe -FileName WordpressDriveBoot\bin\x64\Release\WordpressDriveSetup_64.exe

deploy:
  release: WordpressDrive-v$(APPVEYOR_BUILD_VERSION)
  description: 'Prerelease'
  provider: GitHub
  auth_token:
    secure: UYCMPPzbi/a4gZvxr5fNEY7yzHzOVMcEEjBgClu8WRZXiS15RHConewJjKqIdULE
  artifact: WordpressDriveFiles,WordpressDriveSetup.msi,WordpressDriveFull.exe,WordpressDriveFiles_x64,WordpressDriveSetup\bin\x64\Release\WordpressDriveSetup_x64.msi,WordpressDriveBoot\bin\x64\Release\WordpressDriveSetup_64.exe
  draft: true
  prerelease: true
  on:
    branch: main                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
