version: 1.0.{build}

image: Visual Studio 2017

#configuration: Debug

#platform: x64

environment:
  matrix:
  
  - job_name: Build

  - job_name: x86, Release
    platform: x86
    configuration: Release
    job_group: PlattformBuild
    job_depends_on: Build

  - job_name: x64, Release
    platform: x64
    configuration: Release
    job_group: PlattformBuild
    job_depends_on: Build
    
  - job_name: Deploy
    job_depends_on: PlattformBuild
   
    
before_build:
- start /wait msiexec /i WordpressDriveBoot\external\winfsp-1.7.20172.msi /qn ADDLOCAL=ALL
- cmd: nuget restore
build:
  verbosity: normal

for:
  -
    matrix:
      only:
        - job_name: x86, Release
        
    artifacts: 
      - path: WordpressDrive\bin\$(configuration)
        name: WordpressDriveFiles
      - path: WordpressDriveSetup\bin\$(configuration)\WordpressDriveSetup.msi
        name: WordpressDriveSetup
      - path: WordpressDriveBoot\bin\$(configuration)\WordpressDriveSetup.exe
        name: WordpressDriveFull
  -
    matrix:
      only:
        - job_name: x64, Release
        
    artifacts: 
      - path: WordpressDrive\bin\$(platform)\$(configuration)
        name: WordpressDriveFiles_x64
      - path: WordpressDriveSetup\bin\$(platform)\$(configuration)\WordpressDriveSetup.msi
        name: WordpressDriveSetup_x64
      - path: WordpressDriveBoot\bin\$(platform)\$(configuration)\WordpressDriveSetup.exe
        name: WordpressDriveFull_x64
  -
    matrix:
      only:
        - job_name: Deploy
        
    deploy:
      release: WordpressDrive-v$(APPVEYOR_BUILD_VERSION)
      description: 'Prerelease'
      provider: GitHub
      auth_token:
        secure: UYCMPPzbi/a4gZvxr5fNEY7yzHzOVMcEEjBgClu8WRZXiS15RHConewJjKqIdULE
      artifact: WordpressDriveFiles,WordpressDriveSetup,WordpressDriveFull,WordpressDriveFiles_x64,WordpressDriveSetup_x64,WordpressDriveFull_x64
      draft: true
      prerelease: true
      on:
        branch: main                 # release from master branch only
        APPVEYOR_REPO_TAG: true        # deploy on tag push only



#artifacts: 
# - path: WordpressDrive\bin\$(platform)\$(configuration)
#   name: WordpressDriveFiles
# - path: WordpressDriveSetup\bin\$(configuration)\WordpressDriveSetup.msi
#   name: WordpressDriveSetup
# - path: WordpressDriveBoot\bin\$(configuration)\WordpressDriveSetup.exe
#   name: WordpressDriveFull

#deploy:
#  release: WordpressDrive-v$(APPVEYOR_BUILD_VERSION)
#  description: 'Prerelease'
#  provider: GitHub
#  auth_token:
#    secure: UYCMPPzbi/a4gZvxr5fNEY7yzHzOVMcEEjBgClu8WRZXiS15RHConewJjKqIdULE
#  artifact: WordpressDriveFiles,WordpressDriveSetup,WordpressDriveFull          # upload all NuGet packages to release assets
#  draft: false
#  prerelease: false
#  on:
#    branch: main                 # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
