version: 1.0.{build}

image: Visual Studio 2017

configuration: Debug

platform: x86

before_build:
- start /wait msiexec /i WordpressDriveBoot\external\winfsp-1.7.20172.msi /qn ADDLOCAL=ALL
- cmd: nuget restore
build:
  verbosity: normal

artifacts: 
 - path: WordpressDrive\bin\$(platform)\$(configuration)
   name: WordpressDriveFiles
 - path: WordpressDriveSetup\bin\$(configuration)\WordpressDriveSetup.msi
   name: WordpressDriveSetup
 - path: WordpressDriveBoot\bin\$(configuration)\WordpressDriveSetup.exe
   name: WordpressDriveFull
