version: 1.0.{build}

image: Visual Studio 2017

configuration: Release

platform:
- x86
- x64
    
before_build:
- start /wait msiexec /i WordpressDriveBoot\external\winfsp-1.7.20172.msi /qn ADDLOCAL=ALL
- cmd: nuget restore

build:
  verbosity: normal
  parallel: true

artifacts: 
  - path: WordpressDrive\bin\$(configuration)
    name: WordpressDriveFiles
  - path: WordpressDriveSetup\bin\$(configuration)\WordpressDriveSetup.msi
    name: WordpressDriveSetup
  - path: WordpressDriveBoot\bin\$(configuration)\WordpressDriveSetup.exe
    name: WordpressDriveFull
  - path: WordpressDrive\bin\$(platform)\$(configuration)
    name: WordpressDriveFiles_x64
  - path: WordpressDriveSetup\bin\$(platform)\$(configuration)\WordpressDriveSetup.msi
    name: WordpressDriveSetup_x64
  - path: WordpressDriveBoot\bin\$(platform)\$(configuration)\WordpressDriveSetup.exe
    name: WordpressDriveFull_x64

deploy:
  release: WordpressDrive-v$(APPVEYOR_BUILD_VERSION)
  description: 'Prerelease'
  provider: GitHub
  auth_token:
    secure: UYCMPPzbi/a4gZvxr5fNEY7yzHzOVMcEEjBgClu8WRZXiS15RHConewJjKqIdULE
  artifact: WordpressDriveFiles,WordpressDriveSetup,WordpressDriveFull,WordpressDriveFiles_x64,WordpressDriveSetup_x64,WordpressDriveFull_x64
  draft: true
  prerelease: true
  on:
    branch: main                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
