version: 1.0.{build}

image: Visual Studio 2017

configuration: Debug

platform: x64

before_build:
- start /wait msiexec /i WordpressDriveBoot\external\winfsp-1.7.20172.msi /qn ADDLOCAL=ALL
- cmd: nuget restore
build:
  verbosity: normal

artifacts: 
 - path: WordpressDrive\bin\$(configuration)
   name: WordpressDrive.exe
